name: Access Private Repository

on:
  # Trigger manually
  workflow_dispatch:

jobs:
  access-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Before
        id: debug_before
        run: |
          echo Display workspace $GITHUB_WORKSPACE content
          dir $GITHUB_WORKSPACE

      - name: Generate app installation token
        id: github_app_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.GHA_APP_PK }}
          APP_ID: ${{ secrets.GHA_APP_ID }}

      - name: Checkout private repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          repository: msfred/Workflow-Demos
          path: imported
          token: ${{ steps.github_app_token.outputs.app_token }}

      - name: Debug After
        id: debug_after
        run: |
          echo Display workspace $GITHUB_WORKSPACE content
          dir $GITHUB_WORKSPACE
          echo ---
          echo Display workspace $GITHUB_WORKSPACE/imported content
          dir $GITHUB_WORKSPACE/imported

#      - name: Star Wars Name
#        id: sw
#        uses: $GITHUB_WORKSPACE/imported/.github/actions/star-wars-name
#        with:
#          FirstName: Joesph
#          LastName: Biden
#          BirthCity: Scranton
#          MaidenName: Finnegan

#      - name: Display the Star Wars name
#        run: |
#          echo 'Joe Biden's Star Wars name: ${{steps.sw.outputs.StarWarsName}}'
