# This is a basic workflow to help you get started with Actions
name: PR Labeler

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Explicitly set permissions when environment/organization/repository sets to restrictive mode
    permissions:
      #actions: read|write|none
      #checks: read|write|none
      contents: read
      #deployments: read|write|none
      #discussions: read|write|none
      #issues: read|write|none
      #packages: read|write|none
      #pages: read|write|none
      pull-requests: write
      #repository-projects: read|write|none
      #security-events: read|write|none
      #statuses: read|write|none

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Add labels to pull requests
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
