name: React App - CI/CD Workflow

on:
  # Trigger when code committed to the main branch
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Trigger manually
  workflow_dispatch:

env:
  artifact-ui: ui
  artifact-api: api

jobs:

  # Build React app
  build-ui:
    name: Build React app
    uses: msfred/templates/.github/workflows/build-react.yml@main
    with:
      artifact: ${{ env.artifact-ui }}

  # Deploy React app
  deploy-dev-ui:
    name: Deploy to development
    uses: msfred/templates/.github/workflows/deploy-webapp.yml@main
    with:
      artifact: ${{ env.artifact-ui }}
      environment: development
