name: React App - CI/CD Workflow

on:
  # Trigger when code committed to the main branch
  push:
    branches: [ main ]

  # Trigger manually
  workflow_dispatch:

jobs:

  # Build React app
  build:
    name: Build React app
    uses: msfred/.github/.github/workflows/build-react.yml@main
    with:
      project: MyReactApp
    secrets:
      token: ${{ secrets.token }}

  deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      url: ${{ matrix.url }}
    strategy:
      matrix:
        environment: ['development', 'production']
        include:
          - environment: development
            url: https://dev.hr-product.msfred.org
          - environment: production
            url: https://hr-product.msfred.com
    steps:
      - name: Debug step for the Depoly to ${{ matrix.environment }} job
        run: echo "Starting the deploy to ${{ matrix.environment }}"
