name: React App - CI

on:
  # Trigger when code committed to the main branch
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Trigger manually
  workflow_dispatch:

env:
  artifact: ui
  webAppName: app-hrsampleproduct-ui

jobs:

  # Build React app
  build-ui:
    name: Build React app
    uses: msfred/templates/.github/workflows/build-react.yml@main
    with:
      artifact: ${{ env.artifact }}
      path: ui

  # Deploy React app
  deploy-dev-ui:
    name: Deploy to development
    needs: build-ui
    uses: msfred/templates/.github/workflows/deploy-webapp.yml@main
    with:
      artifact: $artifact
      environment: development
      webAppName: $webAppName
